name: Old validation time

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Validate workflow
    steps:      
      - name: Identify changed yml files # Identifies files added, modified, copied or renamed
        run: |
            pwd
        
          
