title: File

on:
  workflow_dispatch:

jobs-to-run:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Validate workflow
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: PWD
        run: |
            cd .github/scripts
            node test.js
        
          
