name: GitHub Workflows Schema Validation

on:
  pull_request: 
    paths:
        - '.github/workflows/*.yml'
        - '.github/workflows/*.yaml'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate workflow schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@a59f800cbb60ed483623848e31be67659a2940f8 #version https://github.com/tj-actions/changed-files/releases/tag/v18.7
        with:
          path: .github/workflows 
          files: |
            .github/workflows/*.yml
            .github/workflows/*.yaml
  
      - name: Install dependencies
        run: |
            npm install ajv@8.11.0
            npm install axios@0.27.2
            npm install js-yaml@4.1.0
            npm install @actions/core@1.8.0
            
      - name: Run script to validate schema
        uses: actions/github-script@v6
        with:
          script: |
            let files = `${{ steps.changed-files.outputs.all_changed_files }}`
            const script = require('.github/scripts/validate-workflow-schema.js');
            script(files);
