name: GitHub Workflows Schema Validation

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate workflow schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          path: .github/workflows

      - name: Install dependencies
        run: |
            npm install ajv@8.11.0
            npm install axios
            npm install js-yaml
            npm install @actions/core
            
      - name: Run script to validate schema
        uses: actions/github-script@v6
        with:
          script: |
            let files = `${{ steps.changed-files.outputs.all_changed_files }}`
            const script = require('.github/scripts/validate-workflow-schema.js');
            script(files);
