name: Validate Workflow Again Pls

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Validate workflow schema
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7

      - run: |
            npm install ajv@8.11.0
            npm install axios
            npm install js-yaml
            npm install @actions/core

      - uses: actions/github-script@v6
        id: validate-schema
        with:
          script: |
            let files = `${{ steps.changed-files.outputs.all_changed_files }}`
            const script = require('.github/scripts/validate-workflow-schema.js');
            script(files);
            
         
